FROM openjdk:17.0.2-slim-buster

WORKDIR /
RUN mkdir /dir /Results
COPY Java/main.class .
COPY Filesystem/Regular/dir/0.txt /dir
COPY Filesystem/Regular/dir/1.txt /dir
COPY Filesystem/Regular/dir/2.txt /dir
COPY Filesystem/Regular/dir/3.txt /dir
COPY Filesystem/Regular/dir/4.txt /dir
COPY Filesystem/Regular/dir/5.txt /dir
COPY Filesystem/Regular/dir/6.txt /dir
COPY Filesystem/Regular/dir/7.txt /dir
COPY Filesystem/Regular/dir/8.txt /dir
COPY Filesystem/Regular/dir/9.txt /dir
COPY Filesystem/Regular/dir/10.txt /dir
COPY Filesystem/Regular/dir/11.txt /dir
COPY Filesystem/Regular/dir/12.txt /dir
COPY Filesystem/Regular/dir/13.txt /dir
COPY Filesystem/Regular/dir/14.txt /dir
COPY Filesystem/Regular/dir/15.txt /dir